### ISSUE TITLE
Hogwarts bot

### ISSUE THREAD

**Issue by XanMaverick** [MinusGix/DiscordModelHogwartsBot#4]
I am having the same issue as the previous posters and have tried the solution posted in thread 1. I have restarted the bot (using control+c) and have tried various role names in the config file as well as some of the things you listed in thread 3 

![code](https://user-images.githubusercontent.com/40638035/45340406-6e7f6580-b564-11e8-84e1-0f4bf9e4b740.png)

**Comment by MinusGix** [comment]
(I'll assume you didn't leave the bot token blank and removed it from your post for security, which is good.)

I'm not sure what the issue here is, as it should be working (Assuming they have the right roles). Perhaps try with a role that does not have a space? It shouldn't be causing any issues, but I don't really know.
Sorry :/

**Comment by MinusGix** [comment]
I took a look at the code (It's been ages since I coded this), and I realized something. The roles in the config file have to be lowercase. (The roles in your discord server don't have to be though!) because of a dumb decision when I coded it I forgot to convert both to lowercase.
So changing the role names to lowercase should work. If it doesn't it's a different error.

**Comment by XanMaverick** [comment]
Thank you for getting back to me, I will try this solution and get back to you

**Comment by MinusGix** [comment]
I'll assume you either got it working, or no longer care about it, and close this.
