### ISSUE TITLE
Permissions issues

### ISSUE THREAD

**Issue by Alicsejunn** [MinusGix/DiscordModelHogwartsBot#7]
Hi !

Everything works for a while but when i put a 3rd permissions and load it, i have this error message : 
![image](https://user-images.githubusercontent.com/34971146/51202149-5b0f4d00-18fe-11e9-92e7-96f242eea03b.png)

So I decide to return to the last working with only one permission but, the message didn't change...

Here is my configuration.

![image](https://user-images.githubusercontent.com/34971146/51202212-83974700-18fe-11e9-8658-593aa5892327.png)

Thank you !

**Comment by MinusGix** [comment]
You posted your bot token in the second image, so you should go to the discord bot api page and get a new token. Because someone could read the bot token and use it to control the bot to do whatever they wanted which is bad! (In the Bot tab for your bot, click 'Regenerate' and use that new token.) You shouldn't share tokens!  
  
As for your issue, I'm not 100% sure. Not sure what you mean by 'third permissions', I'll assume you mean the 'doAllOfTheAbove' part. 
I think the issue is that the bot doesn't have permissions to send messages in that channel, as I tested it and that error seems to happen when it can't send messages in that channel. Making so it can, should hopefully fix it.

**Comment by Alicsejunn** [comment]
Hi !

I don't send the censured picture... So i get a new token, thanks :)

For the permissions, I write it like this :

"doAllOfTheAbove": [
            "directrices"
        ]
,
        "doAllOfTheAbove": [
            "prefets"
        ]
,
        "doAllOfTheAbove": [
            "fantomes de poudlard"
        ]

It seems to work so... I'm supposed that"s the right way to do ?

I don't know if the problem was the bot's permission, I just delete him and create him again and know it works. So, i let it like this.

I don't think I changed a lot about permissions but maybe my changes not be saved previously, so he don't have the Administrator's. Human error I think, my bad !

Thank you for you answer, hope that you work on new bot maybe :p

**Comment by MinusGix** [comment]
I'm glad you got it working :)
